### ISSUE TITLE
How to Send presence

### ISSUE THREAD

**Issue by othreecodes** [PaulFreund/xmpp#6]
Hello, Im using this library in a Win 8.1 client and i was wondering how to send an online presence

**Comment by coder2000** [comment]
Simply create and send a new presence tag. It should be in the tags.jabber namespace

**Comment by othreecodes** [comment]
here is the snippet im using to send

```c#

private void XmppClient_OnConnected(object sender, EventArgs e)
        {
            
            LogD("XMPP Connect: ","Connected");
            var presence = new XMPP.tags.jabber.client.presence();
            presence.type = XMPP.tags.jabber.client.presence.typeEnum.subscribe;
            
            getClient().Send(presence);
        }

```

It doesn't seem to be sending it

**Comment by coder2000** [comment]
There should be a log file where you can see what is being sent. I am not as familiar with this fork.

**Comment by othreecodes** [comment]
Ive figuered it out... I was sending the presence at "OnConnected" 
I sent it at "OnReady" and it worked.
