### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by akoepe** [PaulFreund/xmpp#9]
Hy! When connecting to the chat server from my client app I get an exception. It only occures if I try using SSL(TLS). It might be because of invalid or selfsigned certificate. Is it somehow possible to ignore this exception, so it doesn't reject the certificate?

**Comment by coder2000** [comment]
This is an area of deficiency where the library is concerned. In my original it is setup to automatically allow any valid certificates without prompting. The ideal method would be to present all certificates to the user for validation. I will hopefully be addressing this in my original version soon but as this fork is written differently it will need to be adapted or done separately.

**Comment by PaulFreund** [comment]
When I wrote Chat Microsoft was not allowing any self signed certificates with .Net Core, I think I have read that this might have changed with Windows 10/Universal Apps but this might need changes to the code and a different runtime target.

**Comment by akoepe** [comment]
Thanks a lot for the answers. How difficult would it be to change these in the code, which part should actually be changed? I only need the Send/Receive message functions and already changed a few parameters in your code so even if the other parts have bugs and errors it would be a perfect temporary solution for me. If it isn't too much effort I can try it on my own though it would help if you could point me in the right direction.(if it is too difficult just forget it)

Thanks again!

**Comment by PaulFreund** [comment]
I think your best option is to just get a free SSL certificate from LetsEncrypt, otherwise you can read the Documentation of StreamSocket from .Net, it is used in common/Manager.cs and common/Connection.cs. I doubt it will be very hard to port. Also look at the network if there is a more advanced fork of this library as I am no longer maintaining it.

**Comment by akoepe** [comment]
Alright, I will see what I can do. Thanks a lot for your help, I really appreciate the effort.
